<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-05-01T19:17:10+05:30
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.5',
    'version_db_installed' => '20201116182100',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1619876814,
    ],
];
