<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-05-01T19:13:41+05:30
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Pankaj Rai',
        ],
    ],
];
